version: '3.5'

services:
  server:
    build: api/
    ports: 
      - "8081:3000"
    restart: always
    networks:
      - mysql
    environment:
      DB_USERNAME: root        
      DB_PASSWORD: password
      DB_IP: db
  
  front:
    build: front/
    ports: 
      - "8080:8080"
    restart: unless-stopped
  
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: countofmoney
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql

networks:
  mysql:
    name: mysql